name: NBP – kursy walut (API NBP, od 2021)

on:
  schedule:
    - cron: '0 9 * * *'   # codziennie o 09:00 UTC+0
  workflow_dispatch:

permissions:
  contents: write

jobs:
  save:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run NBP rates downloader
        run: python3 scripts/save_nbp_rates.py

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # dodaj pliki
          git add docs/exc || true

          # sprawdź, czy są zmiany
          git diff --staged --quiet || (
            # zsynchronizuj z remote
            git pull --rebase origin main

            # commit
            git commit -m "NBP: add exchange rates $(date -u +'%Y-%m-%d')"

            # push
            git push
          )
